# Generated by Django 4.1.1 on 2022-09-28 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hope_construction.models.files.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialHCModel',
            fields=[
                ('id', models.AutoField(db_column='t_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteAuthorName', models.CharField(blank=True, db_column='t_hc_quote_author_name', max_length=225, null=True, verbose_name='Quote Author Name')),
                ('quoteAuthorImage', models.PositiveIntegerField(db_column='t_hc_quote_author_image', default=0, null=True)),
                ('quoteAuthorTitle', models.CharField(blank=True, db_column='t_hc_quote_author_title', max_length=225, null=True, verbose_name='Quote Author Title')),
                ('quoteText', models.TextField(blank=True, db_column='t_hc_quote_text', null=True, verbose_name='Quote Text')),
                ('image', models.PositiveIntegerField(db_column='t_hc_image', default=0, null=True)),
                ('video', models.PositiveIntegerField(db_column='t_hc_video', default=0, null=True)),
                ('creationDate', models.DateTimeField(db_column='t_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='t_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='t_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Testimonial_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='t_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Testimonial_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'hc_testimonial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubscriberHCModel',
            fields=[
                ('id', models.AutoField(db_column='s_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_column='s_hc_email', max_length=254, null=True, verbose_name='email')),
                ('creationDate', models.DateTimeField(db_column='s_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='s_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='s_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='s_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Our Subscribers',
                'db_table': 'hc_subscriber',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SliderHCModel',
            fields=[
                ('id', models.AutoField(db_column='s_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='s_hc_title', max_length=225, null=True, verbose_name='Title')),
                ('subTitle', models.CharField(blank=True, db_column='s_hc_sub_title', max_length=225, null=True, verbose_name='Sub Title')),
                ('description', models.TextField(blank=True, db_column='s_hc_description', null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, db_column='s_hc_link', null=True, verbose_name='Link')),
                ('image', models.PositiveIntegerField(db_column='s_hc_image', default=0, null=True)),
                ('creationDate', models.DateTimeField(db_column='s_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='s_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='s_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Slider_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='s_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Slider_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'hc_sliders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceHCModel',
            fields=[
                ('id', models.AutoField(db_column='s_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='s_hc_title', max_length=225, null=True, verbose_name='Title')),
                ('text', models.TextField(blank=True, db_column='s_hc_text', null=True, verbose_name='Text')),
                ('image', models.PositiveIntegerField(db_column='s_hc_image', default=0, null=True)),
                ('icon', models.PositiveIntegerField(db_column='s_hc_icon', default=0, null=True)),
                ('creationDate', models.DateTimeField(db_column='s_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='s_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='s_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='s_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Our Services',
                'db_table': 'hc_services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessageHCModel',
            fields=[
                ('id', models.AutoField(db_column='m_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, db_column='m_hc_fullname', max_length=225, null=True, verbose_name='Text')),
                ('email', models.CharField(blank=True, db_column='m_hc_email', max_length=225, null=True, verbose_name='Text')),
                ('subject', models.CharField(blank=True, db_column='m_hc_subject', max_length=225, null=True, verbose_name='Text')),
                ('message', models.TextField(blank=True, db_column='m_hc_message', null=True, verbose_name='Text')),
                ('creationDate', models.DateTimeField(db_column='m_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='m_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='m_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='m_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Contact Us',
                'db_table': 'hc_message',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactInfoHCModel',
            fields=[
                ('id', models.AutoField(db_column='ci_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='ci_hc_location', max_length=225, null=True, verbose_name='Location')),
                ('email', models.EmailField(blank=True, db_column='ci_hc_email', max_length=225, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_column='ci_hc_phone', max_length=225, null=True, verbose_name='Phone')),
                ('whatsapp', models.CharField(blank=True, db_column='ci_hc_whatsapp', max_length=225, null=True, verbose_name='Whatsapp')),
                ('facebook', models.URLField(blank=True, db_column='ci_hc_facebook', max_length=225, null=True, verbose_name='Facebook')),
                ('twitter', models.TextField(blank=True, db_column='ci_hc_twitter', null=True, verbose_name='Twitter')),
                ('instagram', models.TextField(blank=True, db_column='ci_hc_instagram', null=True, verbose_name='Instagram')),
                ('mondayToFriday', models.TextField(blank=True, db_column='ci_hc_monday_to_friday', null=True, verbose_name='Monday To Friday Time')),
                ('saturday', models.TextField(blank=True, db_column='ci_hc_saturday', null=True, verbose_name='Saturday')),
                ('sundayAndHolidays', models.TextField(blank=True, db_column='ci_hc_sunday_and_holidays', null=True, verbose_name='Sundays and Holidays')),
                ('creationDate', models.DateTimeField(db_column='ci_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='ci_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='ci_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactInfo_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='ci_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactInfo_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Infos',
                'db_table': 'hc_contact_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AboutHCModel',
            fields=[
                ('id', models.AutoField(db_column='a_hc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, db_column='a_hc_text', null=True, verbose_name='Text')),
                ('creationDate', models.DateTimeField(db_column='a_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='a_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='a_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='About_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='a_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='About_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Us',
                'db_table': 'hc_about',
                'managed': True,
            },
        ),
    ]
