# Generated by Django 4.1.1 on 2022-09-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthcmodel',
            options={'managed': False, 'verbose_name': 'About', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='contactinfohcmodel',
            options={'managed': False, 'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Infos'},
        ),
        migrations.AlterModelOptions(
            name='messagehcmodel',
            options={'managed': False, 'verbose_name': 'Message', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='servicehcmodel',
            options={'managed': False, 'verbose_name': 'Service', 'verbose_name_plural': 'Our Services'},
        ),
        migrations.AlterModelOptions(
            name='sliderhcmodel',
            options={'managed': False, 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterModelOptions(
            name='subscriberhcmodel',
            options={'managed': False, 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Our Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='testimonialhcmodel',
            options={'managed': False, 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
