# Generated by Django 4.1.1 on 2022-09-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0002_alter_abouthcmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfohcmodel',
            options={'managed': True, 'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Infos'},
        ),
    ]
