# Generated by Django 4.1.1 on 2022-09-28 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hope_construction.models.files.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hope_construction', '0005_alter_contactinfohcmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagehcmodel',
            options={'managed': False, 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.CreateModel(
            name='FilesHCModel',
            fields=[
                ('id', models.AutoField(db_column='f_hc_id', primary_key=True, serialize=False)),
                ('attachment', models.FileField(db_column='f_hc_attachment', default=None, upload_to=hope_construction.models.files.main.renameFile)),
                ('filename', models.CharField(blank=True, db_column='f_hc_filename', max_length=1000, null=True, verbose_name='Filename')),
                ('creationDate', models.DateTimeField(db_column='f_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='f_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='f_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Files_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='f_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Files_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'hc_files',
                'managed': True,
            },
        ),
    ]
