# Generated by Django 4.1.1 on 2022-09-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0006_alter_messagehcmodel_options_fileshcmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileshcmodel',
            options={'managed': False, 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
