# Generated by Django 4.1.1 on 2022-09-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0008_galleryhcmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryhcmodel',
            options={'managed': False, 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
