# Generated by Django 4.1.1 on 2022-09-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0009_alter_galleryhcmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderhcmodel',
            options={'managed': True, 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
    ]
