# Generated by Django 4.1.1 on 2022-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0010_alter_sliderhcmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderhcmodel',
            name='linkText',
            field=models.CharField(blank=True, db_column='s_hc_link_text', max_length=50, null=True, verbose_name='Link Text'),
        ),
    ]
