# Generated by Django 4.1.1 on 2022-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0013_alter_fileshcmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshcmodel',
            name='fileType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Video'), (2, 'Image')], db_column='pdm_account_type', default=1, null=True),
        ),
    ]
