# Generated by Django 4.1.1 on 2022-09-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0019_bannerhcmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerhcmodel',
            options={'managed': False, 'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
    ]
