# Generated by Django 4.1.1 on 2022-09-30 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hope_construction', '0020_alter_bannerhcmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoHCModel',
            fields=[
                ('id', models.AutoField(db_column='b_hc_id', primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(db_column='b_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='b_hc_update_date', verbose_name='Update Date')),
                ('createdBy', models.ForeignKey(db_column='b_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logo_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('logoDark', models.OneToOneField(db_column='t_hc_logo_dark', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logo_HC_Model_logoDark', to='hope_construction.fileshcmodel', verbose_name='Logo Light')),
                ('logoLight', models.OneToOneField(db_column='t_hc_logo_light', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logo_HC_Model_logoLight', to='hope_construction.fileshcmodel', verbose_name='Logo Light')),
                ('updatedBy', models.ForeignKey(db_column='b_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logo_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'db_table': 'hc_logos',
                'managed': True,
            },
        ),
    ]
