# Generated by Django 4.1.1 on 2022-09-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0021_logohcmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logohcmodel',
            options={'managed': False, 'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
    ]
