# Generated by Django 4.1.1 on 2022-10-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hope_construction', '0022_alter_logohcmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterImageHCModel',
            fields=[
                ('id', models.AutoField(db_column='ci_hc_id', primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(db_column='ci_hc_creation_date', verbose_name='Creation Date')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='ci_hc_update_date', verbose_name='Update Date')),
                ('centerImage', models.OneToOneField(db_column='ci_hc_center_image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Center_Image_HC_Model_centerImage', to='hope_construction.fileshcmodel', verbose_name='CenterImage')),
                ('createdBy', models.ForeignKey(db_column='ci_hc_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Center_Image_HC_Model_createdBy', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(db_column='ci_hc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Center_Image_HC_Model_updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Center Image',
                'verbose_name_plural': 'Center Images',
                'db_table': 'hc_center_mages',
                'managed': True,
            },
        ),
    ]
