# Generated by Django 4.1.1 on 2022-10-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope_construction', '0023_centerimagehcmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerimagehcmodel',
            options={'managed': False, 'verbose_name': 'Center Image', 'verbose_name_plural': 'Center Images'},
        ),
    ]
