# Generated by Django 4.0.3 on 2022-03-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('token_key', models.CharField(db_index=True, max_length=8)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Individual Member User'), (3, 'Organization Member User')], default=1, null=True)),
                ('user', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Akwaaba Auth Token',
                'verbose_name_plural': 'Akwaaba Auth Tokens',
                'db_table': 'akwaaba_auth_token',
                'managed': True,
            },
        ),
    ]
