# Generated by Django 4.1.1 on 2022-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtoken',
            options={},
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User')], default=1, null=True),
        ),
        migrations.AlterModelTable(
            name='authtoken',
            table=None,
        ),
    ]
